In [1]:
# Importing Libraries:

import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# loading data from question 3: 

path = "pokemon.xlsx"
pokemon = pd.read_excel(path)

pokemon.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [4]:
df = pokemon

# Task 1: Get all Pokemons whose spawn rate is less than 5%

In [5]:
df['spawn_time'].isnull().sum() # there are 6 null values

6

In [6]:
# converting spawn time in minutes format:
temp_df = df['spawn_time'].str.split(":")
df["spawn_min"] = None
for i in range(len(temp_df)):
    if pd.isnull(df["spawn_time"][i]):
        continue
    else:
        # df['spawn_min'] = 0
        df['spawn_min'][i] = (int(temp_df[i][0])*60) + int(temp_df[i][1])

/var/folders/gv/yrj7qx0d6t5gcg_h5bmfd6xc0000gn/T/ipykernel_12943/1629924649.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spawn_min'][i] = (int(temp_df[i][0])*60) + int(temp_df[i][1])

In [7]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,1200
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,525
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140

In [8]:

import pandas as pd
df["spawn_rate"] = None 
for i in range(len(df)):
    if pd.isnull(df["spawn_min"][i]):
        continue
    else:
        df['spawn_rate'][i] = (df['spawn_chance'][i] * (df['avg_spawns'][i]) * 100) / int(df['spawn_min'][i])

/var/folders/gv/yrj7qx0d6t5gcg_h5bmfd6xc0000gn/T/ipykernel_12943/1276101078.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spawn_rate'][i] = (df['spawn_chance'][i] * (df['avg_spawns'][i]) * 100) / int(df['spawn_min'][i])

In [9]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min,spawn_rate
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,1200,3.9675
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420,0.042
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690,0.004188
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,525,1.219219
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140,0.001263

In [10]:
# final result:
df[df["spawn_rate"] < 5]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min,spawn_rate
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,1200,3.9675
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420,0.042
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690,0.004188
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,525,1.219219
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140,0.001263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,142,142,Aerodactyl,http://www.serebii.net/pokemongo/pokemon/142.png,"['Rock', 'Flying']",1.80 m,59.0 kg,None,NaN,10 km,0.0180,1.80,23:40,NaN,"['Water', 'Electric', 'Ice', 'Rock', 'Steel']",NaN,NaN,1420,0.002282
142,143,143,Snorlax,http://www.serebii.net/pokemongo/pokemon/143.png,['Normal'],2.11 m,460.0 kg,None,NaN,10 km,0.0160,1.60,23:40,NaN,['Fighting'],NaN,NaN,1420,0.001803
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,401,2.244389
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",717,0.005579
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",1418,0.000009

-----

# Task 2: Get all Pokemons that have less than 4 weaknesses:

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    int64
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    object
 6   weight          151 non-null    object
 7   candy           151 non-null    object
 8   candy_count     70 non-null     float64
 9   egg             151 non-null    object
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    float64
 12  spawn_time      145 non-null    object
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
 17  spawn_min       145 non-null    object
 18  spawn_rate      145 non-null    object
dtypes: float64(3), int64(2), object(14)
memory usage: 22.5+ KB

In [12]:

import pandas as pd
import ast

df['weaknesses'] = df['weaknesses'].apply(ast.literal_eval) # it changes object to list 

df['weaknesses'].apply(len)

0      4
1      4
2      4
3      3
4      3
      ..
146    3
147    3
148    4
149    3
150    3
Name: weaknesses, Length: 151, dtype: int64

In [13]:
# final Result:
weakness_threshold = 4
pokemon_with_less_than_4_weaknesses = pokemon[df['weaknesses'].apply(len) < weakness_threshold]
pokemon_with_less_than_4_weaknesses[['num', 'name', 'weaknesses']]

     num        name               weaknesses
3      4  Charmander    [Water, Ground, Rock]
4      5  Charmeleon    [Water, Ground, Rock]
5      6   Charizard  [Water, Electric, Rock]
6      7    Squirtle        [Electric, Grass]
7      8   Wartortle        [Electric, Grass]
..   ...         ...                      ...
145  146     Moltres  [Water, Electric, Rock]
146  147     Dratini     [Ice, Dragon, Fairy]
147  148   Dragonair     [Ice, Dragon, Fairy]
149  150      Mewtwo       [Bug, Ghost, Dark]
150  151         Mew       [Bug, Ghost, Dark]

[102 rows x 3 columns]

----

### Task 3: Get all Pokemons that have no multipliers at all

In [14]:
df[df["multipliers"].isnull()]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min,spawn_rate
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690,0.004188
5,6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':...",814,0.000118
8,9,9,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,['Water'],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,NaN,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '...",6,0.074817
11,12,12,Butterfree,http://www.serebii.net/pokemongo/pokemon/012.png,"['Bug', 'Flying']",1.09 m,32.0 kg,Caterpie Candy,NaN,Not in Eggs,0.0220,2.20,05:23,NaN,"[Fire, Electric, Ice, Flying, Rock]",NaN,"[{'num': '010', 'name': 'Caterpie'}, {'num': '...",323,0.014985
14,15,15,Beedrill,http://www.serebii.net/pokemongo/pokemon/015.png,"['Bug', 'Poison']",0.99 m,29.5 kg,Weedle Candy,NaN,Not in Eggs,0.0510,5.10,04:50,NaN,"[Fire, Flying, Psychic, Rock]",NaN,"[{'num': '013', 'name': 'Weedle'}, {'num': '01...",290,0.08969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,145,Zapdos,http://www.serebii.net/pokemongo/pokemon/145.png,"['Electric', 'Flying']",1.60 m,52.6 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Ice, Rock]",NaN,NaN,None,None
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Water, Electric, Rock]",NaN,NaN,None,None
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",1418,0.000009
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN,None,None
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN,None,None

----

### Task 4: Get all Pokemons that do not have more than 2 evolutions

In [15]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min,spawn_rate
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,1200,3.9675
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420,0.042
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690,0.004188
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,525,1.219219
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140,0.001263

In [16]:
pokemon_without_candy = df[df['candy'].isnull()]
pokemon_without_candy

Empty DataFrame
Columns: [id, num, name, img, type, height, weight, candy, candy_count, egg, spawn_chance, avg_spawns, spawn_time, multipliers, weaknesses, next_evolution, prev_evolution, spawn_min, spawn_rate]
Index: []

In [17]:
list_of_pokemons = df['candy'].unique()
list_of_pokemons

array(['Bulbasaur Candy', 'Charmander Candy', 'Squirtle Candy',
       'Caterpie Candy', 'Weedle Candy', 'Pidgey Candy', 'Rattata Candy',
       'Spearow Candy', 'Ekans Candy', 'Pikachu Candy', 'Sandshrew Candy',
       'Nidoran ♀ (Female) Candy', 'Nidoran ♂ (Male) Candy',
       'Clefairy Candy', 'Vulpix Candy', 'Jigglypuff Candy',
       'Zubat Candy', 'Oddish Candy', 'Paras Candy', 'Venonat Candy',
       'Diglett Candy', 'Dugtrio', 'Meowth Candy', 'Psyduck Candy',
       'Mankey Candy', 'Growlithe Candy', 'Poliwag Candy', 'Abra Candy',
       'Machop Candy', 'Bellsprout Candy', 'Tentacool Candy',
       'Geodude Candy', 'Ponyta Candy', 'Slowpoke Candy',
       'Magnemite Candy', 'None', 'Doduo Candy', 'Seel Candy',
       'Grimer Candy', 'Shellder Candy', 'Gastly Candy', 'Drowzee Candy',
       'Krabby Candy', 'Voltorb Candy', 'Exeggcute Candy', 'Cubone Candy',
       'Koffing Candy', 'Rhyhorn Candy', 'Horsea Candy', 'Goldeen Candy',
       'Staryu Candy', 'Magikarp Candy', 'Eevee Candy', 'Omanyte Candy',
       'Kabuto Candy', 'Dratini Candy'], dtype=object)

In [18]:
pokemon_with_evolution = df['candy'].value_counts().to_dict()

In [19]:
pokemon_with_evolution

{'None': 27,
 'Bulbasaur Candy': 3,
 'Nidoran ♂ (Male) Candy': 3,
 'Eevee Candy': 3,
 'Gastly Candy': 3,
 'Geodude Candy': 3,
 'Bellsprout Candy': 3,
 'Charmander Candy': 3,
 'Abra Candy': 3,
 'Poliwag Candy': 3,
 'Oddish Candy': 3,
 'Machop Candy': 3,
 'Nidoran ♀ (Female) Candy': 3,
 'Pidgey Candy': 3,
 'Squirtle Candy': 3,
 'Caterpie Candy': 3,
 'Weedle Candy': 3,
 'Dratini Candy': 3,
 'Paras Candy': 2,
 'Venonat Candy': 2,
 'Shellder Candy': 2,
 'Jigglypuff Candy': 2,
 'Drowzee Candy': 2,
 'Krabby Candy': 2,
 'Voltorb Candy': 2,
 'Exeggcute Candy': 2,
 'Cubone Candy': 2,
 'Koffing Candy': 2,
 'Rhyhorn Candy': 2,
 'Horsea Candy': 2,
 'Goldeen Candy': 2,
 'Staryu Candy': 2,
 'Magikarp Candy': 2,
 'Vulpix Candy': 2,
 'Kabuto Candy': 2,
 'Grimer Candy': 2,
 'Seel Candy': 2,
 'Doduo Candy': 2,
 'Spearow Candy': 2,
 'Meowth Candy': 2,
 'Psyduck Candy': 2,
 'Mankey Candy': 2,
 'Growlithe Candy': 2,
 'Pikachu Candy': 2,
 'Zubat Candy': 2,
 'Ekans Candy': 2,
 'Rattata Candy': 2,
 'Tentacool Candy': 2,
 'Sandshrew Candy': 2,
 'Ponyta Candy': 2,
 'Slowpoke Candy': 2,
 'Clefairy Candy': 2,
 'Magnemite Candy': 2,
 'Dugtrio': 1,
 'Omanyte Candy': 1,
 'Diglett Candy': 1}

In [20]:
type(pokemon_with_evolution)

dict

In [21]:
pokemon_with_eval_greater_than_2 = []
pokemon_with_eval_less_than_2 = []
for k, v in pokemon_with_evolution.items():
    name = k.split()[0]
    if v > 3:
        pokemon_with_eval_greater_than_2.append(name)  
    else:
        pokemon_with_eval_less_than_2.append(name)

print("pokemon who have less than 2 evolutions", pokemon_with_eval_less_than_2)
print("-----------")
print("pokemon who have more than 2 evolutions", pokemon_with_eval_greater_than_2)

pokemon who have less than 2 evolutions ['Bulbasaur', 'Nidoran', 'Eevee', 'Gastly', 'Geodude', 'Bellsprout', 'Charmander', 'Abra', 'Poliwag', 'Oddish', 'Machop', 'Nidoran', 'Pidgey', 'Squirtle', 'Caterpie', 'Weedle', 'Dratini', 'Paras', 'Venonat', 'Shellder', 'Jigglypuff', 'Drowzee', 'Krabby', 'Voltorb', 'Exeggcute', 'Cubone', 'Koffing', 'Rhyhorn', 'Horsea', 'Goldeen', 'Staryu', 'Magikarp', 'Vulpix', 'Kabuto', 'Grimer', 'Seel', 'Doduo', 'Spearow', 'Meowth', 'Psyduck', 'Mankey', 'Growlithe', 'Pikachu', 'Zubat', 'Ekans', 'Rattata', 'Tentacool', 'Sandshrew', 'Ponyta', 'Slowpoke', 'Clefairy', 'Magnemite', 'Dugtrio', 'Omanyte', 'Diglett']
-----------
pokemon who have more than 2 evolutions ['None']

pokemon with more than two evolutions does not exist.

In [22]:
# if we consider null values as no evolution then: 

list(pokemon_without_candy['name'])

[]

In [23]:
pokemon_with_eval_less_than_2.extend(list(pokemon_without_candy['name']))
print("updated list of pokemon with eval less than 2", pokemon_with_eval_less_than_2)
print("number of pokemon's: ", len(pokemon_with_eval_less_than_2))

updated list of pokemon with eval less than 2 ['Bulbasaur', 'Nidoran', 'Eevee', 'Gastly', 'Geodude', 'Bellsprout', 'Charmander', 'Abra', 'Poliwag', 'Oddish', 'Machop', 'Nidoran', 'Pidgey', 'Squirtle', 'Caterpie', 'Weedle', 'Dratini', 'Paras', 'Venonat', 'Shellder', 'Jigglypuff', 'Drowzee', 'Krabby', 'Voltorb', 'Exeggcute', 'Cubone', 'Koffing', 'Rhyhorn', 'Horsea', 'Goldeen', 'Staryu', 'Magikarp', 'Vulpix', 'Kabuto', 'Grimer', 'Seel', 'Doduo', 'Spearow', 'Meowth', 'Psyduck', 'Mankey', 'Growlithe', 'Pikachu', 'Zubat', 'Ekans', 'Rattata', 'Tentacool', 'Sandshrew', 'Ponyta', 'Slowpoke', 'Clefairy', 'Magnemite', 'Dugtrio', 'Omanyte', 'Diglett']
number of pokemon's:  55

-----

#### New approach:

In [24]:
list(df[df['id']==133]['prev_evolution']) # this makes my previous logic wrong...

[nan]

In [25]:
def convert_to_list(string):
    try:
        return ast.literal_eval(string)
    except (SyntaxError, ValueError):
        return []

df['next_evolution'] = df['next_evolution'].apply(convert_to_list)

In [26]:
for i in range(len(df)):
    if pd.isnull(df['next_evolution']).iloc[i]:
        df.loc[i,'total_evolutions'] =0
    else:
        df.loc[i,'total_evolutions']=len(df['next_evolution'].iloc[i])

In [27]:
filtered_df=df[df['total_evolutions']<=2]
pokemon_with_less_than_2evolutions=len(filtered_df)
pokemon_with_less_than_2evolutions

150

In [28]:
filtered_df

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min,spawn_rate,total_evolutions
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,1200,3.9675,2.0
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420,0.042,1.0
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[Fire, Ice, Flying, Psychic]",[],"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690,0.004188,0.0
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,525,1.219219,2.0
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140,0.001263,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,401,2.244389,2.0
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",717,0.005579,1.0
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[Ice, Rock, Dragon, Fairy]",[],"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",1418,0.000009,0.0
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",[],NaN,None,None,0.0
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",[],NaN,None,None,0.0

--------

### Task 5: Get all Pokemon who have more than two types of capabilities

In [29]:
def convert_to_list(string):
    try:
        return ast.literal_eval(string)
    except (SyntaxError, ValueError):
        return []

In [30]:

import json

# df['type'] = df['type'].apply(ast.literal_eval)

In [31]:

df[df['type'].apply(len) > 2]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_min,spawn_rate,total_evolutions
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,1200,3.9675,2.0
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420,0.042,1.0
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[Fire, Ice, Flying, Psychic]",[],"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690,0.004188,0.0
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,525,1.219219,2.0
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140,0.001263,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,401,2.244389,2.0
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",717,0.005579,1.0
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[Ice, Rock, Dragon, Fairy]",[],"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",1418,0.000009,0.0
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",[],NaN,None,None,0.0
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",[],NaN,None,None,0.0

In [32]:
df['type'].apply(len) > 2

0      True
1      True
2      True
3      True
4      True
       ...
146    True
147    True
148    True
149    True
150    True
Name: type, Length: 151, dtype: bool

In [33]:
# There are no pokemon more than two types of capabilities

----